name: Node.js CI - Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Get dependencies
        run: npm install --no-audit --no-fund; cp config.json.sample config.json
        
      - name: Run tests
        env:
          CI: true
        run: npm test
